<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{92f14351-dcbb-423d-9f1d-1757ec898e20}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Hethong : FB_Systems;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Hethong();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>